/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/input.glb --transform 
Files: public/input.glb [414.78KB] > /home/snoou/project/main/mini-project-react/input-transformed.glb [46.96KB] (89%)
Author: ZahraAmini (https://sketchfab.com/ZahraAmini)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crop-top-and-skirt-5ae8c0d2a73949d6878da17db3b37a2b
Title: crop top and skirt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/input-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.FABRIC_3_FRONT_3983} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.FABRIC_5_FRONT_3993} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/input-transformed.glb')
