/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Jacket.glb --transform 
Files: public/Jacket.glb [370.17KB] > /home/snoou/project/main/mini-project-react/Jacket-transformed.glb [66.77KB] (82%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Jacket-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="mesh_char_115009" geometry={nodes.mesh_char_115009.geometry} material={materials._060_Angry} morphTargetDictionary={nodes.mesh_char_115009.morphTargetDictionary} morphTargetInfluences={nodes.mesh_char_115009.morphTargetInfluences} scale={100} />
    </group>
  )
}

useGLTF.preload('/Jacket-transformed.glb')
